[gcp_service_account]
type = "service_account"
project_id = "pendataan-industri-kejambon"
private_key_id = "a89a18e029b673770a86883b95e3b7d89b04265c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC8aV5wtD2sWPD2
ubq0kiuv+qnkrrH42rNUWQIiaSTzw0i0rRfejT7Sm3IZkUQSBKruIrl6pAFxu8a6
FUhVFXT9cHMlPHebYV3umH2ghJbmDYCbK0f6tWqgcaXHmMEMyzb6rtk56I+fJ35u
SSOejsSma3IyLMJR0Mjel/r0fMrHbQXukSIeWrz8BYDzpbrv/PQzfeMVm9eFaDEa
0BIWD7cBH/u9zEzgqFiJ0ZjhWIO1t2B3BAF1tVsQZU+1Yn99D6875rHEVprs9OWK
mA5CsFDh8CjG5wqtintJF0tQRRjqvwtvF/zkIesa63L4SZBZ4uE2Mz/Nu1gF17du
9reSwfmnAgMBAAECggEAHRbtqFwDu6Tdy1Igs/lvelOqwG6CdugZUPgPHs36ERLB
GngxG8DWBsFOTAlEJ74FwA+ncHp66Jrz004u5UgTUH/4nzKnStutG4X6u3pNLAbA
qPR1QA2bgVsam+cHQ1jqy6iMTGcOKaX43ME5GSV00jb7oiiL9gLUyJ1Rd0b/Levw
1udpCJUccM/hLXWjAUn9nrc28Ur5PcNYcP2JVxioJtVL9k7YUj37Ig63THRl3Ugo
lGG706U1HGHE3UpvJsmFZhIyEIwqDi1Z6mHAaJB0RzAdzIdmdeUisyPsqJRQmXz1
QPutn41BAhB42CO2RlOt9GdNYS47W2nKygeGMg5bQQKBgQDoMYOdnys1Car+VMba
Ar/dhI5XZzSmMZgrqeqcdDSfllYK6i7jNta1iduSdW1j4PDw0WSE0CbzZ+V5bTqt
r2Jqem5uSoJPBuW5IMmkXBtk6kdO3C8tfVKIZN3MLniPIIm0Fiiwz0d94QaahIWX
CL/g6Tk2Vh8mMkkmjLXe04imwQKBgQDPurGNjfHV/+6BBKH4JDqMWWzdusbqRAxh
4SDoFkMYI3GPR3Gtl5hY+7BqTWoCZwj0LlZZ9pRLGsvIMCnVFjvBKseJzeViWA05
GG/Imp8SNH8ecFLQuHUpA6gtaY0ON1BhiD9yDR1OY8qjByz4zBwGGuA2AjbkRxLk
u7AZPDFiZwKBgC698PnlFeSaaqLCXDl8/jTQv3rW2uFt8G0xynnuZr2NnQqbdA7n
djebZelI3FmT6c0AyhR2drDfRHG6TGq0eMJonRx0wWC5SbuH3y/IHvektfApIRIu
PVQZwhCddkWRzkbDgzN8tq6fgx3N+bqa102mhY7rrV+aFeG9x8rwmHzBAoGBAJNp
/Y5i6Pfgw7SzQO4DZ7kpzOQdJAQjflYHmX6aLcr3fCMdpEJ4jhi3pB4MCerii6wd
JhJ5tgsGXQ8XfthFCuquHSRiBSKhMeEOwmUttS0KLBvBwkN0Y1BT1AlGGl+4SUat
lbiuLdnvX2IKOZPl5Q1ADVTGhYXCGlpQB0whNzqJAoGBAIOkT96oE9xxy2L4TnD2
dpBecT3qJJBrmpPpdcrGjeyrOOuQ3HQ5nAUKZDdheZq928AFzRF6yVUcqzD3q0SL
Hpvk5DX5Z2toKytFYKg4uAP1u0mg8n7/wRRE6VHiyF4axgJaCGAL0/elAwLmvAQ8
oMoG571CmP3zfdmy+rExLjp8
-----END PRIVATE KEY-----"""
client_email = "pendataan-industri-kejambon@pendataan-industri-kejambon.iam.gserviceaccount.com"
client_id = "100365409662629170597"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pendataan-industri-kejambon%40pendataan-industri-kejambon.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
